// Shared mock data + threat helpers, lifted in spirit from the codebase.

const SHAME_LINES = [
  "Another day, another rug. Stay frosty degens.",
  "If you're on this list, your mom is disappointed.",
  "Eat dirt, scamboy.",
  "Certified rug merchant. Handle with disgust.",
  "Your tokenomics were just 'take money and run.'",
  "The blockchain remembers. So do we.",
  "Your whitepaper was just a napkin that said 'lol.'",
  "Plot twist: the real utility was the friends we scammed along the way.",
];

const REPORTS = [
  {
    id: "r1",
    rank: 1,
    type: "deployer",
    identifier: "0x8a3F19c4b6d2E14e0b9c81f9b73a4eAaC7d2901B",
    reason: "Deployed JEETCOIN, pulled $1.2M liquidity at exactly 0.420 ATH. Same wallet has deployed 14 tokens in 9 days.",
    authorNickname: "rugslayer.eth",
    authorColor: "#ff3b9a",
    authorTitle: "Bounty Hunter",
    confirmCount: 287,
    commentCount: 142,
    bountyCount: 6,
    threat: "LEGENDARY",
    roastTitle: "the Rugnarok",
    createdAt: "3h ago",
    chain: "SOL",
  },
  {
    id: "r2",
    rank: 2,
    type: "twitter",
    identifier: "moonboi_dev",
    reason: "Shilled 'community takeover' for the 6th time this month. Each one ended in a stealth dump within 4 hours.",
    authorNickname: "etherdetective",
    authorColor: "#7c5cff",
    authorTitle: "Watchdog",
    confirmCount: 144,
    commentCount: 88,
    bountyCount: 2,
    threat: "LEGENDARY",
    roastTitle: "Serial Soft-Rug Enjoyer",
    createdAt: "11h ago",
    chain: "ETH",
  },
  {
    id: "r3",
    rank: 3,
    type: "deployer",
    identifier: "0x42aeFf09812bB1c9aA4f8d11de2C29c66E901aaA",
    reason: "Honeypot. Buy tax 1%, sell tax 99%. Contract has a hidden setMaxTx that only the owner can call.",
    authorNickname: "soliditysnitch",
    authorColor: "#34d399",
    authorTitle: "Code Auditor",
    confirmCount: 92,
    commentCount: 41,
    bountyCount: 1,
    threat: "EXTREME",
    roastTitle: "Honeypot Honey, No Honey",
    createdAt: "1d ago",
    chain: "BSC",
  },
  {
    id: "r4",
    rank: 4,
    type: "twitter",
    identifier: "alphacaller_99",
    reason: "Sold his 'private alpha group' for 0.5 ETH/month. Picks are scraped from public Discords with a 6-hour delay.",
    authorNickname: "groupchatgremlin",
    authorColor: "#fb923c",
    authorTitle: "Fresh Degen",
    confirmCount: 53,
    commentCount: 27,
    bountyCount: 0,
    threat: "EXTREME",
    roastTitle: "The Discount Alpha Guy",
    createdAt: "2d ago",
    chain: "ETH",
  },
  {
    id: "r5",
    rank: 5,
    type: "deployer",
    identifier: "0x9100c441D9eC4F2b81fEd4dfBb12CE6cD401fffe",
    reason: "Renounced ownership, then mints from a backdoored proxy on a 24h timer. Three projects dead this way.",
    authorNickname: "0xforensics",
    authorColor: "#22d3ee",
    authorTitle: "Bounty Hunter",
    confirmCount: 38,
    commentCount: 19,
    bountyCount: 3,
    threat: "HIGH",
    roastTitle: "Renounced In Name Only",
    createdAt: "2d ago",
    chain: "ETH",
  },
  {
    id: "r6",
    rank: 6,
    type: "twitter",
    identifier: "based_quant_dev",
    reason: "Bot army. 40k followers, 38k of them registered in the same week. Promotes presales for a 30% cut.",
    authorNickname: "botbusterella",
    authorColor: "#f472b6",
    authorTitle: "Watchdog",
    confirmCount: 21,
    commentCount: 12,
    bountyCount: 0,
    threat: "HIGH",
    roastTitle: null,
    createdAt: "3d ago",
    chain: "—",
  },
  {
    id: "r7",
    rank: 7,
    type: "deployer",
    identifier: "0x77abEEdc119fF1b1cE2cE3441b8a2c1F71eFe211",
    reason: "Pretends to LP-lock. The 'lock' contract has an emergency-withdraw the deployer added in commit 14.",
    authorNickname: "etherdetective",
    authorColor: "#7c5cff",
    authorTitle: "Watchdog",
    confirmCount: 14,
    commentCount: 7,
    bountyCount: 0,
    threat: "EXTREME",
    roastTitle: "Schrödinger's Locked LP",
    createdAt: "4d ago",
    chain: "SOL",
  },
  {
    id: "r8",
    rank: 8,
    type: "twitter",
    identifier: "lightspeed_ape",
    reason: "Repeated wash-trading on his own picks to fake volume. Same 5 wallets every time.",
    authorNickname: "rugslayer.eth",
    authorColor: "#ff3b9a",
    authorTitle: "Bounty Hunter",
    confirmCount: 9,
    commentCount: 4,
    bountyCount: 0,
    threat: "MEDIUM",
    roastTitle: null,
    createdAt: "5d ago",
    chain: "—",
  },
];

const TOP_USERS = [
  { nick: "rugslayer.eth", color: "#ff3b9a", title: "Bounty Hunter", xp: 4820, mood: "vengeful", reports: 31 },
  { nick: "etherdetective", color: "#7c5cff", title: "Watchdog", xp: 3960, mood: "caffeinated", reports: 28 },
  { nick: "soliditysnitch", color: "#34d399", title: "Code Auditor", xp: 3110, mood: "smug", reports: 19 },
  { nick: "0xforensics", color: "#22d3ee", title: "Bounty Hunter", xp: 2740, mood: "patient", reports: 22 },
  { nick: "botbusterella", color: "#f472b6", title: "Watchdog", xp: 2180, mood: "tired", reports: 17 },
  { nick: "groupchatgremlin", color: "#fb923c", title: "Fresh Degen", xp: 940, mood: "feral", reports: 6 },
  { nick: "honeypot_hunter", color: "#facc15", title: "Code Auditor", xp: 870, mood: "amused", reports: 8 },
  { nick: "txn_diver", color: "#60a5fa", title: "Fresh Degen", xp: 520, mood: "curious", reports: 4 },
];

const LIVE_FEED = [
  { who: "rugslayer.eth", what: "confirmed", target: "0x8a3F…901B", color: "#ff3b9a", t: "12s" },
  { who: "groupchatgremlin", what: "reported", target: "@alphacaller_99", color: "#fb923c", t: "1m" },
  { who: "etherdetective", what: "commented on", target: "@moonboi_dev", color: "#7c5cff", t: "2m" },
  { who: "soliditysnitch", what: "added bounty to", target: "0x42ae…1aaA", color: "#34d399", t: "4m" },
  { who: "0xforensics", what: "confirmed", target: "0x9100…fffe", color: "#22d3ee", t: "6m" },
  { who: "botbusterella", what: "reported", target: "@based_quant_dev", color: "#f472b6", t: "9m" },
  { who: "rugslayer.eth", what: "roasted", target: "@lightspeed_ape", color: "#ff3b9a", t: "12m" },
];

const COMMENTS = [
  {
    user: "soliditysnitch",
    color: "#34d399",
    title: "Code Auditor",
    body: "Pulled the verified source. Line 218 has a `_skipFee` mapping the deployer can flip on their own wallet only. This is a deliberate backdoor, not a bug.",
    t: "2h",
    score: 184,
  },
  {
    user: "rugslayer.eth",
    color: "#ff3b9a",
    title: "Bounty Hunter",
    body: "Same wallet funded by Tornado 0.1 ETH 9 hours before deploy. I'll post the trail in a sec.",
    t: "1h",
    score: 92,
  },
  {
    user: "groupchatgremlin",
    color: "#fb923c",
    title: "Fresh Degen",
    body: "lost 4 sol to this clown. on this list till i die",
    t: "47m",
    score: 28,
  },
];

const THREAT_STYLE = {
  LOW: { color: "#22c55e", label: "LOW", fire: "" },
  MEDIUM: { color: "#eab308", label: "MEDIUM", fire: "🔥" },
  HIGH: { color: "#f97316", label: "HIGH", fire: "🔥🔥" },
  EXTREME: { color: "#ef4444", label: "EXTREME", fire: "🔥🔥🔥" },
  LEGENDARY: { color: "#ff1744", label: "LEGENDARY", fire: "💀" },
};

function shortId(id, type) {
  if (type === "twitter") return "@" + id;
  if (id.length > 14) return id.slice(0, 6) + "…" + id.slice(-4);
  return id;
}

Object.assign(window, {
  SHAME_LINES, REPORTS, TOP_USERS, LIVE_FEED, COMMENTS, THREAT_STYLE, shortId,
});
